### ISSUE TITLE
Apigility CORS without zfr-cors - simplier is better?

### ISSUE THREAD

**Issue by ivanvujisic** [zf-fr/zfr-cors#24]
OK, I get stuck with zfr-cors installation, so I get mad and put this:

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods', 'PUT, GET, POST, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Authorization, WWW-Authenticate, Origin, X-Requested-With, Content-Type, Accept');

in Apigility /public/index.php, above this line:

Zend\Mvc\Application::init($appConfig)->run();

So, it "seems" to me I resolved CORS issue with Apigility (confirmed by AngularJS front end developer), but I'm sure you guys have some comments on this.

Thanks.

**Comment by cvuorinen** [comment]
I was also having issues with zfrCors (more specifically this: https://github.com/zf-fr/zfr-cors/issues/14 and this: https://github.com/zf-fr/zfr-cors/issues/18) so I decided to set the CORS headers manually and disable zfrCors, since I don't need any advanced CORS functionality.

I ended up with a solution where I get the Response object in a module bootstrap and set the headers using that, which I think is a better way than calling the header function directly in index.php.

So I added the following method to a `Module.php` file:
```
    public function onBootstrap(MvcEvent $event)
    {
        // Set CORS headers to allow all requests
        $headers = $event->getResponse()->getHeaders();
        $headers->addHeaderLine('Access-Control-Allow-Origin: *');
        $headers->addHeaderLine('Access-Control-Allow-Methods: PUT, GET, POST, PATCH, DELETE, OPTIONS');
        $headers->addHeaderLine('Access-Control-Allow-Headers: Authorization, Origin, X-Requested-With, Content-Type, Accept');
    }
```

**Comment by bakura10** [comment]
Hi,

Actually, I've myself ended up NOT using ZfrCors. The problem is that you need to have the overhead of the whole application bootstrapping just to send headers.

A much better solution is actually to handle that on Apache side (although it offers you less flexibility, but for most cases, this is enough). Here is my VirtualHost for instance:

```
 <VirtualHost *:80>
          ServerName default
          ServerAlias *
          DocumentRoot "/var/www/html/public"

          # First, let's handle CORS requests
          SetEnvIfNoCase Access-Control-Request-Method "(GET|POST|PUT|DELETE|OPTIONS)" IsPreflight=1
          SetEnvIfNoCase Origin "https://(url1.com|url2.com)$" AccessControlAllowOrigin=$0

          Header always set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
          Header always set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" env=IsPreflight
          Header always set Access-Control-Allow-Headers "Content-Type, Authorization, Accept" env=IsPreflight
          Header always set Access-Control-Max-Age "7200" env=IsPreflight

          RewriteEngine On
          RewriteCond %{REQUEST_METHOD} OPTIONS
          RewriteCond %{ENV:IsPreflight} 1
          RewriteRule ^(.*)$ $1 [R=200,L]

          <Directory "/var/www/html/public">
              DirectoryIndex index.php
              AllowOverride All
              Order allow,deny
              Allow from all

              RewriteEngine On
              RewriteCond %{REQUEST_FILENAME} -s [OR]
              RewriteCond %{REQUEST_FILENAME} -l [OR]
              RewriteCond %{REQUEST_FILENAME} -d
              RewriteRule ^.*$ - [NC,L]
              RewriteRule ^.*$ index.php [NC,L]
          </Directory>
      </VirtualHost>
```
